Exploratory-Data-Analysis(EDA)

Setup library

In [2]:
%pip install -q -U numpy pandas seaborn matplotlib

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns

Load Dataset

In [4]:
# Load the built-in Titanic dataset
df = sns.load_dataset('titanic')

# Look at the first 5 rows to understand the columns
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Adding few columns for demonstrating data issues

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
# Add a new column 'passenger_id' with unique values for each passenger
df['passenger_id'] = np.arange(1, len(df)+1)

# Add a constant column with the same value for all rows
df['contant_col'] = 1

#create a dirty version of embark_town column
df['embark_town_dirty'] = df['embark_town'].copy()

# select a few random rows only non-missing values
sample_idx = df['embark_town_dirty'].dropna().sample(6, random_state=42).index

# Apply simple dirty transformations to the selected rows
df.loc[sample_idx [0:2], 'embark_town_dirty'] = df.loc[sample_idx [0:2], 'embark_town_dirty'].str.upper()  # Convert to uppercase
df.loc[sample_idx [2:4], 'embark_town_dirty'] = df.loc[sample_idx [2:4], 'embark_town_dirty'].str.strip().apply(lambda x: f' {x} ')  # Add extra spaces
df.loc[sample_idx [4:6], 'embark_town_dirty'] = 'unknown'  # Replace with unknown

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,contant_col,embark_town_dirty
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1,Southampton
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1,Cherbourg
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1,Southampton
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1,Southampton
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1,Southampton

1. Basic Dataset Overview

In [7]:
print(df.shape)
print(df.dtypes)
print('---------------')
print(df.info())

(891, 18)
survived                int64
pclass                  int64
sex                       str
age                   float64
sibsp                   int64
parch                   int64
fare                  float64
embarked                  str
class                category
who                       str
adult_male               bool
deck                 category
embark_town               str
alive                     str
alone                    bool
passenger_id            int64
contant_col             int64
embark_town_dirty         str
dtype: object
---------------
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   survived           891 non-null    int64
 1   pclass             891 non-null    int64
 2   sex                891 non-null    str
 3   age                714 non-null    float64
 4   sibsp              891 non-null    int64
 5   parch              891 non-null    int64
 6   fare               891 non-null    float64
 7   embarked           889 non-null    str
 8   class              891 non-null    category
 9   who                891 non-null    str
 10  adult_male         891 non-null    bool
 11  deck               203 non-null    category
 12  embark_town        889 non-null    str
 13  alive              891 non-null    str
 14  alone              891 non-null    bool
 15  passenger_id       891 non-null    int64
 16  contant_col        891 non-null    int64
 17  embark_town_dirty  889 non-null    str
dtypes: bool(2), category(2), float64(2), int64(6), str(6)
memory usage: 101.5 KB
None

In [8]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'passenger_id', 'contant_col', 'embark_town_dirty'],
      dtype='str')

In [9]:
df.nunique()

survived               2
pclass                 3
sex                    2
age                   88
sibsp                  7
parch                  7
fare                 248
embarked               3
class                  3
who                    3
adult_male             2
deck                   7
embark_town            3
alive                  2
alone                  2
passenger_id         891
contant_col            1
embark_town_dirty      7
dtype: int64

In [10]:
df.describe()

,survived,pclass,age,sibsp,parch,fare,passenger_id,contant_col
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.0
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,446.000000,1.0
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,257.353842,0.0
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000,1.0
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,223.500000,1.0
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,446.000000,1.0
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,668.500000,1.0
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,891.000000,1.0

Missing Values Summary

In [11]:
missing_count = df.isna().sum().sort_values(ascending=False)
missing_percentage = (df.isna().mean()*100).sort_values(ascending=False)

missing_summary = pd.DataFrame({
    
        'missing_count': missing_count, 
        'missing_percentage': missing_percentage
     
     })
print('Missing Values Summary:')
missing_summary

Missing Values Summary:

                   missing_count  missing_percentage
deck                         688           77.216611
age                          177           19.865320
embark_town_dirty              2            0.224467
embarked                       2            0.224467
embark_town                    2            0.224467
survived                       0            0.000000
pclass                         0            0.000000
parch                          0            0.000000
sibsp                          0            0.000000
sex                            0            0.000000
who                            0            0.000000
class                          0            0.000000
fare                           0            0.000000
adult_male                     0            0.000000
alive                          0            0.000000
alone                          0            0.000000
passenger_id                   0            0.000000
contant_col                    0            0.000000

*Duplicate Value Check*

In [12]:
duplicate_mask = df.duplicated()
num_duplicates = duplicate_mask.sum()
print(f'Number of duplicate rows: {num_duplicates}')

Number of duplicate rows: 0

*Data Type Validation*

In [13]:
expected_dtypes = {
    "survived": "int64",
    "pclass": "int64",
    "sex": "category",
    "age": "float64",
    "fare": "float64",
    "embarked": "category",
    "embark_town": "category",
}

for col, expected in expected_dtypes.items():
    if col in df.columns:
        actual_dtype = df[col].dtype
        print(f"{col}: actual = {actual_dtype}, expected = {expected}")

survived: actual = int64, expected = int64
pclass: actual = int64, expected = int64
sex: actual = str, expected = category
age: actual = float64, expected = float64
fare: actual = float64, expected = float64
embarked: actual = str, expected = category
embark_town: actual = str, expected = category

In [14]:
# Fixing a data types if needed
# df['age'] = df['age'].astype('int64')

In [24]:
df = df.rename(columns={"contant_col": "const_columns"})
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'passenger_id', 'const_columns', 'embark_town_dirty'],
      dtype='str')

**Constant and Quasi-Constant Columns**

In [28]:
n_rows = len(df)
print('Number of Rows:', n_rows)
nunique = df.nunique()
constant_col = nunique[nunique==1].index.tolist() 
print('Constant Columns:', constant_col)

quasi_constant_cols = []

for col in df.columns:
    top_freq = df[col].value_counts(normalize=True, dropna=False).values[0]
    if top_freq > 0.95 and col not in constant_col:
        quasi_constant_cols.append(col)

print('Quasi-Constant Columns:', quasi_constant_cols)

Number of Rows: 891
Constant Columns: ['const_columns']
Quasi-Constant Columns: []

In [26]:
nunique = df.nunique()
print('Unique Values per Column:', nunique)

Unique Values per Column: survived               2
pclass                 3
sex                    2
age                   88
sibsp                  7
parch                  7
fare                 248
embarked               3
class                  3
who                    3
adult_male             2
deck                   7
embark_town            3
alive                  2
alone                  2
passenger_id         891
const_columns          1
embark_town_dirty      7
dtype: int64

**Column With All Unique Values**

In [30]:
n_rows = len(df)

column_with_all_unique = []

for col in df.columns:
    unique_count = df[col].nunique()
    if unique_count == n_rows:
        column_with_all_unique.append(col)
print(f"Columns with all unique values: {column_with_all_unique}")

Columns with all unique values: ['passenger_id']